---
- name: Ensure site root folder is present
  ansible.builtin.file:
    state: directory
    path: "{{ r.site_root }}"
    owner: "{{ username }}"
    mode: "755"

- name: Install Python requirements
  become: false
  tags:
    - deploy
    - skip_ansible_lint
  ansible.builtin.pip:
    chdir: "{{ r.site_root }}"
    name: "{{ r.pip_target }}"
    state: latest
    extra_args: "--upgrade --no-cache-dir"
    virtualenv: "{{ r.site_root }}/venv"
    virtualenv_command: /usr/bin/python3 -m venv

- name: Add env file
  tags:
    - deploy
  ansible.builtin.template:
    src: env.j2
    dest: "/etc/profile.d/{{ r.server_name }}.env"
    owner: "{{ username }}"
    mode: "600"

- name: Add service
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ r.server_name }}.service"

- name: Restart the service
  tags:
    - deploy
    - restart
  ansible.builtin.systemd:
    name: "{{ r.server_name }}"
    daemon_reload: "yes"
    enabled: "yes"
    state: restarted

- name: Add HTTPS site configuration
  ansible.builtin.template:
    src: https.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ r.server_name }}.https.conf"

- name: Reload nginx
  tags:
    - deploy
    - certs
  ansible.builtin.service:
    name: nginx
    state: reloaded
